#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
reset=`tput sgr0`


files=`find input -type f`

for file in $files
do
echo "${yellow}input: $file${reset}"
echo
cat $file
echo
echo "${yellow}output:${reset}"
echo

./obfuscare $file

done
